import * as Joi from "joi";

export interface Slot {
    conversation_id: string,
    form_first_name?: string,
    form_last_name?: string,
    form_email?: string,
    form_phone_number?: string,
    form_number_of_attendees?: string,
    form_reception_date?: string,
    form_venue_address?: string,
    form_alcohol_plan?: string,
    form_underwriting_knockouts?: string,
    form_exclude_activities_description?: string,
    form_add_named_insureds_add_secondary?: string,
    form_add_named_insureds_secondary?: string,
    form_add_named_insureds_add_tertiary?: string,
    form_add_named_insureds_tertiary?: string,
    form_add_named_insureds_quarternary?: string,
    form_send_venue_certificate?: string,
    form_venue_name?: string,
    form_venue_email?: string,
    form_provide_venue_email_address?: string,
    form_second_location?: string,
    form_second_location_address?: string,
    form_third_location_check?: string,
    form_third_location_address?: string,
    form_mailing_address?: string,
    form_quote_preference_q?: string,
    wed_ins_cov_peference?: string,
    form_quote_preference_undecided?: string,
    form_quote_preference_cancel_q?: string,
    form_wedding_budget_short?: string,
    conversation_url?: string
}

export const slotSchema = Joi.object({
    conversation_id: Joi.string().required(),
    form_first_name: Joi.string().optional(),
    form_last_name: Joi.string().optional(),
    form_email: Joi.string().optional(),
    form_phone_number: Joi.string().optional(),
    form_number_of_attendees: Joi.string().optional(),
    form_reception_date: Joi.string().optional(),
    form_venue_address: Joi.string().optional(),
    form_alcohol_plan: Joi.string().optional(),
    form_underwriting_knockouts: Joi.string().optional(),
    form_exclude_activities_description: Joi.string().optional(),
    form_add_named_insureds_add_secondary: Joi.string().optional(),
    form_add_named_insureds_secondary: Joi.string().optional(),
    form_add_named_insureds_add_tertiary: Joi.string().optional(),
    form_add_named_insureds_tertiary: Joi.string().optional(),
    form_add_named_insureds_quarternary: Joi.string().optional(),
    form_send_venue_certificate: Joi.string().optional(),
    form_venue_name: Joi.string().optional(),
    form_venue_email: Joi.string().optional(),
    form_provide_venue_email_address: Joi.string().optional(),
    form_second_location: Joi.string().optional(),
    form_second_location_address: Joi.string().optional(),
    form_third_location_check: Joi.string().optional(),
    form_third_location_address: Joi.string().optional(),
    form_mailing_address: Joi.string().optional(),
    form_quote_preference_q: Joi.string().optional(),
    wed_ins_cov_peference: Joi.string().optional(),
    form_quote_preference_undecided : Joi.string().optional(),
    form_quote_preference_cancel_q: Joi.string().optional(),
    form_wedding_budget_short: Joi.string().optional(),
    conversation_url: Joi.string().optional()
});
